theme: jekyll-theme-architect
title: "ASTRA: ISRO Space Tech Hackathon 2026"
description: "Autonomous Space Rendezvous, Docking & Inspection Digital Twin Platform"
show_downloads: false
google_analytics: null
